name: Resource Groups Terraform CI/CD

on:
  push:
    branches:
      - main
      - release/dev
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Lint, Security Check, and Deploy (RG)'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: 'us-east-1'
      TF_VERSION: '1.4.0'
      TFLINT_VERSION: '0.46.1'
      TFSEC_VERSION: '1.28.1'

    defaults:
      run:
        working-directory: resource-groups

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.GH_ACTION_DEPLOY_ROLE }}
        role-session-name: github-actions-session

    - name: Debug AWS Credentials
      run: |
        echo "AWS_REGION=$AWS_REGION"
        aws sts get-caller-identity
    - name: 'Set up Terraform with AWS credentials'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
        cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

    # - name: 'Install TFLint'
    #   run: |
    #     curl -sLo tflint.zip https://github.com/terraform-linters/tflint/releases/download/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip
    #     unzip tflint.zip -d /usr/local/bin/
    #     tflint --version

    # - name: 'Install tfsec'
    #   run: |
    #     curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v${{ env.TFSEC_VERSION }}/tfsec-linux-amd64
    #     chmod +x tfsec
    #     mv tfsec /usr/local/bin/
    #     tfsec --version
      

    - name: 'Terraform Init'
      run: terraform init
      env:
          TFC_TOKEN: ${{ secrets.TFC_API_TOKEN }}

    - name: 'Terraform Format'
      run: terraform fmt

    - name: 'Terraform Validate'
      run: terraform validate

    # - name: 'TFLint'
    #   run: |
    #     tflint --init
    #     tflint

    # - name: 'tfsec'
    #   run: tfsec .

    - name: 'Terraform Plan'
      run: terraform plan

    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
